# Generated by Django 5.2.8 on 2025-11-27 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                ("encounter_date", models.DateTimeField(verbose_name="진료 일시")),
                (
                    "reason",
                    models.TextField(
                        help_text="환자의 주 증상 또는 방문 이유",
                        verbose_name="내원 사유",
                    ),
                ),
                (
                    "facility",
                    models.CharField(
                        help_text="예: 신경외과 외래",
                        max_length=200,
                        verbose_name="진료 부서",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="진료 상태",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당 의사",
                    ),
                ),
            ],
            options={
                "verbose_name": "진료 기록",
                "verbose_name_plural": "진료 기록 목록",
                "db_table": "emr_encounter",
                "ordering": ["-encounter_date"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        help_text="병원 고유 환자 식별 번호 (예: PT-2025-1001)",
                        max_length=50,
                        unique=True,
                        verbose_name="환자 고유 번호",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="이름")),
                ("last_name", models.CharField(max_length=100, verbose_name="성")),
                ("date_of_birth", models.DateField(verbose_name="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="전화번호")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                (
                    "insurance_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="건강보험 번호"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="비상 연락처"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Django User와 1:1 관계 (앱 로그인용)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자 계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "환자",
                "verbose_name_plural": "환자 목록",
                "db_table": "emr_patient",
            },
        ),
        migrations.CreateModel(
            name="MergedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="문서 제목")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("FINAL_REPORT", "Final Report"),
                            ("REFERRAL", "Referral"),
                            ("DISCHARGE_SUMMARY", "Discharge Summary"),
                            ("LAB_RESULT", "Lab Result"),
                        ],
                        max_length=50,
                        verbose_name="문서 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="문서 상태",
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        default=dict,
                        help_text="원본 데이터 ID 참조 (Data Lineage)",
                        verbose_name="참조 데이터",
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        default=dict,
                        help_text="기록 당시의 데이터 스냅샷",
                        verbose_name="스냅샷 데이터",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="emr.encounter",
                        verbose_name="진료 세션",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="서명 의사",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="emr.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "통합 문서",
                "verbose_name_plural": "통합 문서 목록",
                "db_table": "emr_merged_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="emr.patient",
                verbose_name="환자",
            ),
        ),
        migrations.CreateModel(
            name="FormSOAP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="작성 일시")),
                (
                    "subjective",
                    models.TextField(
                        help_text="환자가 호소하는 증상", verbose_name="주관적 소견 (S)"
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        help_text="의사의 관찰 및 검사 결과",
                        verbose_name="객관적 소견 (O)",
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        help_text="1차 진단 또는 평가", verbose_name="평가 (A)"
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        help_text="향후 치료 계획", verbose_name="계획 (P)"
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soap",
                        to="emr.encounter",
                        verbose_name="진료 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "SOAP 차트",
                "verbose_name_plural": "SOAP 차트 목록",
                "db_table": "emr_form_soap",
                "indexes": [
                    models.Index(
                        fields=["encounter"], name="emr_form_so_encount_f31c15_idx"
                    ),
                    models.Index(fields=["-date"], name="emr_form_so_date_e538cd_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FormVitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="측정 일시")),
                (
                    "bps",
                    models.IntegerField(
                        blank=True,
                        help_text="Systolic Blood Pressure",
                        null=True,
                        verbose_name="수축기 혈압 (mmHg)",
                    ),
                ),
                (
                    "bpd",
                    models.IntegerField(
                        blank=True,
                        help_text="Diastolic Blood Pressure",
                        null=True,
                        verbose_name="이완기 혈압 (mmHg)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="체중 (kg)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="신장 (cm)",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="체온 (°C)",
                    ),
                ),
                (
                    "pulse",
                    models.IntegerField(
                        blank=True,
                        help_text="Heart rate",
                        null=True,
                        verbose_name="맥박 (bpm)",
                    ),
                ),
                (
                    "respiration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="호흡수 (회/분)"
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.IntegerField(
                        blank=True,
                        help_text="SpO2",
                        null=True,
                        verbose_name="산소 포화도 (%)",
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Body Mass Index (자동 계산)",
                        max_digits=4,
                        null=True,
                        verbose_name="BMI",
                    ),
                ),
                (
                    "bmi_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Underweight", "Underweight"),
                            ("Normal", "Normal"),
                            ("Overweight", "Overweight"),
                            ("Obese", "Obese"),
                        ],
                        max_length=20,
                        verbose_name="BMI 상태",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="emr.encounter",
                        verbose_name="진료 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "활력 징후",
                "verbose_name_plural": "활력 징후 목록",
                "db_table": "emr_form_vitals",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["encounter", "-date"],
                        name="emr_form_vi_encount_2ba8fd_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["pid"], name="emr_patient_pid_81c174_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="emr_patient_last_na_2ab650_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mergeddocument",
            index=models.Index(
                fields=["patient", "-created_at"], name="emr_merged__patient_04a0e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mergeddocument",
            index=models.Index(
                fields=["encounter"], name="emr_merged__encount_539d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mergeddocument",
            index=models.Index(fields=["status"], name="emr_merged__status_2c712d_idx"),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["patient", "-encounter_date"],
                name="emr_encount_patient_73804b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["doctor", "-encounter_date"],
                name="emr_encount_doctor__0b521a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(fields=["status"], name="emr_encount_status_764b6e_idx"),
        ),
    ]
