# Generated by Django 5.0 on 2025-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0003_patient_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="이메일"),
        ),
    ]
