# Generated by Django 5.0 on 2025-12-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0004_alter_patient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="formsoap",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="formvitals",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="mergeddocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
    ]
