# Generated by Django 5.2.8 on 2025-11-27 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("APPOINTMENT_CONFIRMED", "Appointment Confirmed"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("DIAGNOSIS_READY", "Diagnosis Ready"),
                            ("PRESCRIPTION_READY", "Prescription Ready"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=50,
                        verbose_name="알림 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.TextField(verbose_name="메시지 내용")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="읽은 시각"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="발송 시각"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="예: appointment_id, prescription_id 등",
                        verbose_name="추가 메타데이터",
                    ),
                ),
                (
                    "push_sent",
                    models.BooleanField(default=False, verbose_name="푸시 발송 여부"),
                ),
                (
                    "push_error",
                    models.TextField(
                        blank=True,
                        help_text="FCM 오류 메시지",
                        verbose_name="푸시 발송 오류",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수신자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 기록",
                "verbose_name_plural": "알림 기록 목록",
                "db_table": "notification_log",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-sent_at"],
                        name="notificatio_recipie_f0c3f1_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="notificatio_is_read_1746ff_idx"
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_2b209e_idx",
                    ),
                ],
            },
        ),
    ]
