# Generated by Django 5.0 on 2025-12-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
    ]
