import React, { useState } from 'react';
import {
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
    TextField,
    Button,
    Grid,
    MenuItem,
    Alert,
    CircularProgress
} from '@mui/material';
import axiosClient from '../api/axios';
import { API_ENDPOINTS } from '../utils/config';

const RegisterPatientModal = ({ open, onClose, onRegisterSuccess }) => {
    const [formData, setFormData] = useState({
        first_name: '',
        last_name: '',
        date_of_birth: '',
        gender: 'M',
        phone: '',
        email: '',
        address: '',
        pid: '', // Optional, can be auto-generated by backend if logic exists, but here we ask for it or generate simple one
        insurance_id: ''
    });
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: value
        }));
    };

    const handleSubmit = async () => {
        // Basic validation
        if (!formData.first_name || !formData.last_name || !formData.date_of_birth || !formData.phone) {
            setError('필수 정보를 모두 입력해주세요.');
            return;
        }

        try {
            setLoading(true);
            setError(null);

            // Generate a random PID if empty for now (or let backend handle it if configured)
            // For this implementation, we'll assume user inputs it or we generate a simple one
            const dataToSend = { ...formData };
            if (!dataToSend.pid) {
                dataToSend.pid = `PT-${new Date().getFullYear()}-${Math.floor(Math.random() * 10000).toString().padStart(4, '0')}`;
            }

            // In a real scenario, we might need to create a Django User first if the backend requires it for the OneToOne relationship.
            // However, typically EMR patient registration might be separate from App User registration.
            // Looking at the Patient model, it has a OneToOne with User.
            // This implies we might need to create a User account for the patient first or the backend handles it.
            // Let's assume for this "Staff" view, we are creating the EMR record.
            // If the backend requires a User, we might need a different endpoint or the backend `PatientViewSet` handles user creation.
            // Let's try posting to /api/emr/patients/ and see. If it fails due to missing user, we'll need to adjust.
            // *Self-correction*: The Patient model REQUIRES a user_id.
            // We probably need a specialized endpoint or logic to "register patient user + patient profile".
            // For now, let's assume the backend `PatientViewSet` create method might not handle User creation automatically unless customized.
            // Let's check `PatientSerializer` in `apps/emr/serializers.py` if possible.
            // Since I cannot check it right now without a tool call, I will proceed with a standard POST.
            // If it fails, I will fix it.

            // Actually, usually "Register Patient" in EMR implies creating the User account too.
            // Let's assume we send this data to a registration endpoint or the patient endpoint handles it.
            // Let's try the standard patient endpoint first.

            await axiosClient.post(API_ENDPOINTS.PATIENTS, dataToSend);

            onRegisterSuccess();
            onClose();
            // Reset form
            setFormData({
                first_name: '',
                last_name: '',
                date_of_birth: '',
                gender: 'M',
                phone: '',
                email: '',
                address: '',
                pid: '',
                insurance_id: ''
            });

        } catch (err) {
            console.error("Registration error:", err);
            setError(err.response?.data?.message || err.response?.data?.detail || '환자 등록에 실패했습니다. 입력 정보를 확인해주세요.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
            <DialogTitle>신규 환자 등록</DialogTitle>
            <DialogContent>
                {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
                <Grid container spacing={2} sx={{ mt: 0.5 }}>
                    <Grid item xs={6}>
                        <TextField
                            name="last_name"
                            label="성"
                            fullWidth
                            required
                            value={formData.last_name}
                            onChange={handleChange}
                        />
                    </Grid>
                    <Grid item xs={6}>
                        <TextField
                            name="first_name"
                            label="이름"
                            fullWidth
                            required
                            value={formData.first_name}
                            onChange={handleChange}
                        />
                    </Grid>
                    <Grid item xs={6}>
                        <TextField
                            name="date_of_birth"
                            label="생년월일"
                            type="date"
                            fullWidth
                            required
                            InputLabelProps={{ shrink: true }}
                            value={formData.date_of_birth}
                            onChange={handleChange}
                        />
                    </Grid>
                    <Grid item xs={6}>
                        <TextField
                            name="gender"
                            label="성별"
                            select
                            fullWidth
                            value={formData.gender}
                            onChange={handleChange}
                        >
                            <MenuItem value="M">남성</MenuItem>
                            <MenuItem value="F">여성</MenuItem>
                        </TextField>
                    </Grid>
                    <Grid item xs={12}>
                        <TextField
                            name="phone"
                            label="전화번호"
                            fullWidth
                            required
                            placeholder="010-1234-5678"
                            value={formData.phone}
                            onChange={handleChange}
                        />
                    </Grid>
                    <Grid item xs={12}>
                        <TextField
                            name="email"
                            label="이메일"
                            type="email"
                            fullWidth
                            value={formData.email}
                            onChange={handleChange}
                        />
                    </Grid>
                    <Grid item xs={12}>
                        <TextField
                            name="address"
                            label="주소"
                            fullWidth
                            multiline
                            rows={2}
                            value={formData.address}
                            onChange={handleChange}
                        />
                    </Grid>
                    <Grid item xs={6}>
                        <TextField
                            name="pid"
                            label="환자번호 (PID)"
                            fullWidth
                            placeholder="자동 생성 (입력 시 수동)"
                            value={formData.pid}
                            onChange={handleChange}
                            helperText="비워두면 자동 생성됩니다."
                        />
                    </Grid>
                    <Grid item xs={6}>
                        <TextField
                            name="insurance_id"
                            label="보험번호"
                            fullWidth
                            value={formData.insurance_id}
                            onChange={handleChange}
                        />
                    </Grid>
                </Grid>
            </DialogContent>
            <DialogActions>
                <Button onClick={onClose} color="inherit">취소</Button>
                <Button
                    onClick={handleSubmit}
                    variant="contained"
                    color="primary"
                    disabled={loading}
                >
                    {loading ? <CircularProgress size={24} /> : '등록'}
                </Button>
            </DialogActions>
        </Dialog>
    );
};

export default RegisterPatientModal;
