# Generated by Django 5.2.8 on 2025-11-27 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("DOCTOR", "Doctor"),
                            ("NURSE", "Nurse"),
                            ("PATIENT", "Patient"),
                        ],
                        default="PATIENT",
                        help_text="시스템 내 사용자 역할 (RBAC)",
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="연락처",
                        max_length=20,
                        verbose_name="전화번호",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="사용자 프로필 사진",
                        null=True,
                        upload_to="profiles/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        blank=True,
                        help_text="Firebase Cloud Messaging 토큰 (Push 알림용)",
                        max_length=255,
                        verbose_name="FCM 토큰",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="사용자 소개 또는 경력",
                        verbose_name="소개",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Django User 모델과 1:1 관계",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필 목록",
                "db_table": "user_profile",
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_profil_user_id_4f95f8_idx"
                    ),
                    models.Index(fields=["role"], name="user_profil_role_c7e6f1_idx"),
                ],
            },
        ),
    ]
