# Generated by Django 5.0 on 2025-11-30 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시간', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시간', verbose_name='수정일시')),
                ('is_active', models.BooleanField(default=True, help_text='False인 경우 소프트 삭제된 상태', verbose_name='활성 상태')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='소프트 삭제된 시간', null=True, verbose_name='삭제일시')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='진료과명')),
                ('location', models.CharField(help_text='예: 본관 3층 301호', max_length=200, verbose_name='위치')),
                ('phone_number', models.CharField(max_length=20, verbose_name='대표 전화번호')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '진료과',
                'verbose_name_plural': '진료과 목록',
                'db_table': 'department',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.department', verbose_name='소속 진료과'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='관리자 승인 상태 (PENDING, APPROVED, REJECTED)', max_length=20, verbose_name='승인 상태'),
        ),
    ]
