# Generated by Django 5.2.8 on 2025-11-27 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="의사 면허 번호"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        help_text="예: Neurology, Neurosurgery",
                        max_length=100,
                        verbose_name="전문 분야",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="소속 부서"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="경력 및 소개")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자 계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "의사",
                "verbose_name_plural": "의사 목록",
                "db_table": "custom_doctor",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="예약 일시")),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="예상 진료 시간 (분)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="예약 상태",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("FIRST_VISIT", "First Visit"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("CHECK_UP", "Check Up"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        max_length=20,
                        verbose_name="방문 유형",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="환자가 입력한 방문 사유",
                        verbose_name="예약 사유",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="PATIENT_APP",
                        help_text="PATIENT_APP, DOCTOR_WEB, NURSE_STATION",
                        max_length=50,
                        verbose_name="생성 경로",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="의사가 추가한 예약 관련 메모",
                        verbose_name="의사 메모",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="emr.patient",
                        verbose_name="환자",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="custom.doctor",
                        verbose_name="담당 의사",
                    ),
                ),
            ],
            options={
                "verbose_name": "예약",
                "verbose_name_plural": "예약 목록",
                "db_table": "custom_appointment",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주치의 여부"),
                ),
                ("assigned_date", models.DateField(verbose_name="배정 날짜")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_patients",
                        to="custom.doctor",
                        verbose_name="의사",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_doctors",
                        to="emr.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "환자-의사 관계",
                "verbose_name_plural": "환자-의사 관계 목록",
                "db_table": "custom_patient_doctor",
            },
        ),
        migrations.CreateModel(
            name="PatientPredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="예: NeuroNova_Brain_v2.1",
                        max_length=100,
                        verbose_name="모델명",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(max_length=20, verbose_name="모델 버전"),
                ),
                (
                    "orthanc_study_uid",
                    models.CharField(
                        blank=True,
                        help_text="DICOM Study Instance UID",
                        max_length=200,
                        verbose_name="Orthanc Study UID",
                    ),
                ),
                (
                    "orthanc_series_uid",
                    models.CharField(
                        blank=True,
                        help_text="DICOM Series Instance UID",
                        max_length=200,
                        verbose_name="Orthanc Series UID",
                    ),
                ),
                (
                    "prediction_class",
                    models.CharField(
                        choices=[
                            ("Glioma", "Glioma"),
                            ("Meningioma", "Meningioma"),
                            ("Pituitary", "Pituitary"),
                            ("No Tumor", "No Tumor"),
                        ],
                        help_text="AI가 예측한 종양 유형",
                        max_length=50,
                        verbose_name="예측 클래스",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="예측 확률 (0~1)", verbose_name="신뢰도 점수"
                    ),
                ),
                (
                    "probabilities",
                    models.JSONField(
                        default=dict,
                        help_text="모든 클래스에 대한 확률 분포",
                        verbose_name="클래스별 확률",
                    ),
                ),
                (
                    "xai_image_path",
                    models.CharField(
                        blank=True,
                        help_text="SHAP/Grad-CAM 히트맵 이미지 경로",
                        max_length=500,
                        verbose_name="XAI 이미지 경로",
                    ),
                ),
                (
                    "feature_importance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="모델이 중요하게 본 특징들",
                        verbose_name="특성 중요도",
                    ),
                ),
                (
                    "doctor_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CORRECT", "Correct"),
                            ("INCORRECT", "Incorrect"),
                            ("AMBIGUOUS", "Ambiguous"),
                            ("NEEDS_REVIEW", "Needs Review"),
                        ],
                        help_text="AI 예측에 대한 의사의 평가",
                        max_length=20,
                        verbose_name="의사 피드백",
                    ),
                ),
                (
                    "doctor_note",
                    models.TextField(
                        blank=True,
                        help_text="의사의 추가 코멘트",
                        verbose_name="의사 소견",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="의사가 검토 완료한 시간",
                        null=True,
                        verbose_name="확정 일시",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_predictions",
                        to="custom.doctor",
                        verbose_name="검토 의사",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="emr.encounter",
                        verbose_name="진료 세션",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="emr.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 진단 결과",
                "verbose_name_plural": "AI 진단 결과 목록",
                "db_table": "custom_prediction_result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                (
                    "medication_code",
                    models.CharField(
                        help_text="표준 약물 코드",
                        max_length=50,
                        verbose_name="약물 코드",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(max_length=200, verbose_name="약물명"),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="1회 투여량", max_length=100, verbose_name="용량"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="예: 3 times/day",
                        max_length=100,
                        verbose_name="투여 빈도",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="예: 7 days", max_length=50, verbose_name="투여 기간"
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("Oral", "Oral"),
                            ("IV", "Intravenous"),
                            ("IM", "Intramuscular"),
                            ("Topical", "Topical"),
                            ("Subcutaneous", "Subcutaneous"),
                        ],
                        max_length=50,
                        verbose_name="투여 경로",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="예: 식후 30분 복용",
                        verbose_name="복용 지시사항",
                    ),
                ),
                (
                    "prescribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="처방 일시"),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="emr.encounter",
                        verbose_name="진료 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방전",
                "verbose_name_plural": "처방전 목록",
                "db_table": "custom_prescription",
                "ordering": ["-prescribed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["license_number"], name="custom_doct_license_866504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["specialty"], name="custom_doct_special_0309fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "-scheduled_at"],
                name="custom_appo_patient_5e9b2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "-scheduled_at"],
                name="custom_appo_doctor__819f32_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="custom_appo_status_336a7f_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["scheduled_at"], name="custom_appo_schedul_ab095e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdoctor",
            index=models.Index(
                fields=["patient", "is_primary"], name="custom_pati_patient_d4553b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdoctor",
            index=models.Index(
                fields=["doctor"], name="custom_pati_doctor__64c6c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientdoctor",
            unique_together={("patient", "doctor")},
        ),
        migrations.AddIndex(
            model_name="patientpredictionresult",
            index=models.Index(
                fields=["patient", "-created_at"], name="custom_pred_patient_fc93a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientpredictionresult",
            index=models.Index(
                fields=["encounter"], name="custom_pred_encount_e33432_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientpredictionresult",
            index=models.Index(
                fields=["prediction_class"], name="custom_pred_predict_2c4367_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientpredictionresult",
            index=models.Index(
                fields=["doctor_feedback"], name="custom_pred_doctor__b3666f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["encounter"], name="custom_pres_encount_0c3ff7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["-prescribed_at"], name="custom_pres_prescri_19e557_idx"
            ),
        ),
    ]
