# Generated by Django 5.0 on 2025-12-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0001_initial"),
        ("emr", "0002_alter_patient_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntigenAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="레코드가 생성된 시간",
                        verbose_name="생성일시",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="레코드가 마지막으로 수정된 시간",
                        verbose_name="수정일시",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 소프트 삭제된 상태",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="소프트 삭제된 시간",
                        null=True,
                        verbose_name="삭제일시",
                    ),
                ),
                (
                    "input_sequence",
                    models.TextField(
                        help_text="분석된 단백질/DNA/RNA 서열", verbose_name="입력 서열"
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        help_text="PROTEIN, DNA, RNA",
                        max_length=20,
                        verbose_name="입력 타입",
                    ),
                ),
                (
                    "prediction_result",
                    models.JSONField(
                        help_text="Task1, Task2, Task3 결과 포함",
                        verbose_name="예측 결과",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antigen_results",
                        to="emr.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "항원 분석 결과",
                "verbose_name_plural": "항원 분석 결과 목록",
                "db_table": "custom_antigen_result",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="custom_anti_patient_193c1c_idx",
                    )
                ],
            },
        ),
    ]
