# Generated by Django 5.0 on 2025-12-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0002_antigenanalysisresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antigenanalysisresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="patientdoctor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="patientpredictionresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="레코드가 생성된 시간",
                verbose_name="생성일시",
            ),
        ),
    ]
